name: Deploy Laravel App
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SERVER_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_IP }} "
          cd /var/www/html/ggssa_portal &&
          git reset --hard HEAD && git clean -df &&
          git pull origin main &&
          composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader &&
          npm ci &&
          npm run build &&
          php artisan migrate --force &&
          php artisan optimize:clear &&
          php artisan config:cache &&
          php artisan route:cache &&
          php artisan filament:cache-components
        "